client-id: keypress
discovery-url: https://keycloak.localhost/auth/realms/applications
encryption-key: yb96KrChmqnEOHuIbBi650T7VDqyTwLZ

scopes:
  - keypress

# Turn on debug
verbose: true

enable-refresh-tokens: true

listen: :80
redirection-url: https://keypress.localhost
upstream-url: http://keypress:80

enable-default-deny: true

# Use gatekeeper like kong, which handles all authentication
# Only whitelist /, everything else requires authentication
resources:
- uri: /
  methods:
  - GET
  white-listed: true
